<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AlbumsRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class AlbumsRepository extends EntityRepository
{
    /**
    x    * @return array\News[]
     */
    public function findAllOrderByCreatedDesc(): array
    {
        return $this->createQueryBuilder('n')
            ->orderBy('n.createdAt', 'DESC')
            ->getQuery()
            ->execute();
    }
}
